server:
  port: 8080

spring:
  application:
    name: gateway
  profiles:
    active: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    datasource:
      url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

  security:
    basic:
      enabled: false


zuul:
  routes:
   skills:
    path: /**
    serviceId: resource-server
    stripPrefix: false

#   imageman:
#    path: /imageman/**
#    serviceId: imageman
#    stripPrefix: false

swagger-ui:
 configuration:
 -
  application-name: resource-server  # ServiceId
  path: /v2/api-docs              # swagger request mapping path
  version: 1.0


assessment:
    time: 5400 # in seconds

hystrix:
  threadpool:
    default:
      # Maximum number of concurrent requests when using thread pools (Default: 10)
      coreSize: 3
      # Maximum LinkedBlockingQueue size - -1 for using SynchronousQueue (Default: -1)
      maxQueueSize: -1
      # Queue size rejection threshold (Default: 5)
      queueSizeRejectionThreshold: 3
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 30000
        requestVolumeThreshold: 2
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 3000
    SendNotification:
      circuitBreaker:
        sleepWindowInMilliseconds: 30000
        requestVolumeThreshold: 2
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000

