#security:
#  oauth2:
#    resource:
#      jwt:
#        key-uri: http://auth.delesio.com:9999/auth/oauth/token_key
#  basic:
#    enabled: false
#  user:
#    name: admin

eureka:
  client:
    service-url:
      defaultZone: http://eureka.techolution.qa:8761/eureka/
  instance:
    hostname: .techolution.com
    status-page-url: http://.techolution.com:${server.port}/info
    health-check-url: http://.techolution.com:${server.port}/health
    home-page-url: http://.techolution.com:${server.port}/

# spring:
#   jpa:
#     show-sql: true
#     hibernate:
#       ddl-auto: update
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQL5Dialect
#   datasource:
#     url: jdbc:mysql://assessment-db/assessment?useSSL=false
#     username: root
#     password: admin123
#     driver-class-name: com.mysql.jdbc.Driver

#   data:
#     mongodb:
#       uri: mongodb://mongo:27017/vrcms

# redis:
#   hostname: redis
#   port: 6380

