version: "2"

services:
    eureka:
    image: screening/eureka
    networks:
      - training-network
    ports:
      - "8761:8761"
    expose:
      - "8761"

  # mongo:
  #   image: mongo
  #   networks:
  #     - my-network
  #   ports:
  #     - "27017:27017"
  #   expose:
      # - "27017"

  # redis:
  #   image: redis
  #   networks:
  #     - my-network
  #   ports:
  #     - "6379:6379"
  #   expose:
  #     - "6379"

  # mysql-db:
  #     image: mysql:latest
  #     environment:
  #       - MYSQL_ROOT_PASSWORD=admin123
  #       - MYSQL_USER=dbuser
  #       - MYSQL_PASSWORD=password
  #       - MYSQL_DATABASE=database_name
  #     networks:
  #       - my-network
  #     ports:
  #       - "3306:3306"
  #     expose:
  #       - "3306"

networks:
  my-network:
    driver: bridge
